- name: starting apache on ubuntu
  service:
    name: apache2
    state: started
    enabled: yes

  when: ansible_distribution == "Ubuntu"


- name: starting apache on Fedora
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"
