- name: create ansible user
  user:
    name: ansible_user
    system: yes
   

- name: copy sudoers_ansible
  copy:
    src: file/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
